Setup

In [2]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [4]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)

print(arr_1d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = np.arange(100).reshape(10, 10)

print(arr_2d)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(60).reshape(4, 5, 3)

print(arr_3d)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


**Explain:**
- What does `.shape` represent?
- Why does contiguous memory matter?


Section 1.2 — dtype & Memory

In [16]:
# TODO:
# Create two arrays with same values but different dtypes

arr_int = np.array([1.2, 2, 3, 4], dtype=np.int32)
print(arr_int)
arr_float = np.array([1, 2.2, 3, 4], dtype=np.float64)
print(arr_float)

[1 2 3 4]
[1.  2.2 3.  4. ]


In [14]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print("Int array bytes:", arr_int.nbytes)
print("Float array bytes:", arr_float.nbytes)


Int array bytes: 16
Float array bytes: 32


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [20]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(20).reshape(5, 4)

A_slice = A[::2]

print(A)
print(A_slice)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]


In [21]:
# TODO:
# Modify A_slice and observe A
A_slice[0, 0] = 999

print(A)


[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]]


Explain:
- Why did the original array change (or not)?


Section 2.2 — Boolean Masking

In [18]:
# TODO:
# Create random array of size 1000

X = np.random.randn(1000)

print(X)


[ 6.21773536e-01 -1.30697379e+00 -6.24599955e-01  9.47670624e-01
 -1.58328886e-01  1.69419534e+00  1.51688720e+00  6.42018776e-01
  1.24066684e-01  5.97399857e-01  5.08963934e-01  1.25026035e-01
 -2.00260748e-01  2.23739622e-01 -1.30004314e+00 -3.88854994e-01
  4.60484775e-01  1.89428797e-01 -5.30590666e-01 -4.50848560e-01
  7.05773739e-01 -4.31001840e-01 -9.57508367e-01 -2.07162336e+00
  1.24454614e-01 -3.41806138e-01  5.98159813e-03 -3.29970472e-01
 -6.16950536e-01  1.55724158e+00  1.29174083e+00 -3.22010663e-01
  1.19736860e+00 -1.12440753e+00  4.63461196e-01 -1.35351589e+00
  1.59857272e+00 -1.60665414e+00 -1.44022337e+00 -8.05638099e-01
 -3.75590500e-01 -5.84665270e-01 -5.04558126e-01 -2.18247225e+00
  8.83786384e-01  5.08059952e-02 -1.19105794e-01 -1.15288244e+00
 -1.09303780e+00 -4.15361942e-02 -1.30532979e+00  7.90462177e-01
 -1.70524737e+00 -4.81513060e-01 -7.29032727e-02 -1.48702467e+00
 -5.06226207e-01 -6.02035885e-01  3.35971272e-01 -7.20786693e-01
  7.02038667e-01  1.26021

In [22]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask

mean_val = X.mean()

greater_than_mean = X[X > mean_val]

print(mean_val)
print(greater_than_mean)


-0.009016410215515648
[6.21773536e-01 9.47670624e-01 1.69419534e+00 1.51688720e+00
 6.42018776e-01 1.24066684e-01 5.97399857e-01 5.08963934e-01
 1.25026035e-01 2.23739622e-01 4.60484775e-01 1.89428797e-01
 7.05773739e-01 1.24454614e-01 5.98159813e-03 1.55724158e+00
 1.29174083e+00 1.19736860e+00 4.63461196e-01 1.59857272e+00
 8.83786384e-01 5.08059952e-02 7.90462177e-01 3.35971272e-01
 7.02038667e-01 1.26021175e+00 1.34609560e-01 1.57159825e+00
 1.32275815e+00 1.42606813e+00 7.21222067e-01 7.59256482e-01
 2.06858165e+00 2.05049454e-01 1.21202507e+00 1.03772617e+00
 2.45300223e-01 7.50912667e-02 1.06108907e-01 6.70970988e-01
 3.14997026e-01 1.21747783e+00 8.61958103e-01 5.65087369e-01
 2.22611074e-01 2.03756421e+00 1.36164663e+00 1.54027523e+00
 1.37233165e+00 7.34961576e-01 1.23851170e+00 1.26773489e+00
 5.76890881e-01 3.85254285e-01 9.35378431e-01 6.26284120e-01
 1.03986327e+00 4.02837997e-01 1.49980162e+00 1.03847121e+00
 7.14140029e-01 1.06383281e+00 2.13688000e-01 1.90636643e+00
 1

In [23]:
# TODO:
# Replace negative values with 0 (no loops)

Positive_Vals = X[X > 0]

print(Positive_Vals)


[6.21773536e-01 9.47670624e-01 1.69419534e+00 1.51688720e+00
 6.42018776e-01 1.24066684e-01 5.97399857e-01 5.08963934e-01
 1.25026035e-01 2.23739622e-01 4.60484775e-01 1.89428797e-01
 7.05773739e-01 1.24454614e-01 5.98159813e-03 1.55724158e+00
 1.29174083e+00 1.19736860e+00 4.63461196e-01 1.59857272e+00
 8.83786384e-01 5.08059952e-02 7.90462177e-01 3.35971272e-01
 7.02038667e-01 1.26021175e+00 1.34609560e-01 1.57159825e+00
 1.32275815e+00 1.42606813e+00 7.21222067e-01 7.59256482e-01
 2.06858165e+00 2.05049454e-01 1.21202507e+00 1.03772617e+00
 2.45300223e-01 7.50912667e-02 1.06108907e-01 6.70970988e-01
 3.14997026e-01 1.21747783e+00 8.61958103e-01 5.65087369e-01
 2.22611074e-01 2.03756421e+00 1.36164663e+00 1.54027523e+00
 1.37233165e+00 7.34961576e-01 1.23851170e+00 1.26773489e+00
 5.76890881e-01 3.85254285e-01 9.35378431e-01 6.26284120e-01
 1.03986327e+00 4.02837997e-01 1.49980162e+00 1.03847121e+00
 7.14140029e-01 1.06383281e+00 2.13688000e-01 1.90636643e+00
 1.05448812e+00 7.708301

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [24]:
# TODO:
# Create A (1000, 50) and b (50,)


A = np.random.randn(1000, 50)
b = np.random.randn(50)

print(A)
print(b)


[[ 0.44906553 -0.22920056  0.5673599  ...  2.0664054  -0.2320645
   1.02684191]
 [ 2.90026872 -0.78914346  0.32396446 ...  1.34656635  0.5825938
  -0.94906955]
 [ 0.30213524 -0.20994923 -0.28887657 ... -0.20443155 -0.42456229
   1.5086864 ]
 ...
 [ 0.24578724 -1.38670491 -0.19448365 ...  1.4110487  -0.29167179
  -0.3665645 ]
 [-1.93414937  0.28028202 -1.32337483 ...  0.62911735 -1.36770742
   1.74799463]
 [ 0.68380062  1.51452257  2.34700037 ...  1.08627689  0.38136707
   1.42071524]]
[ 1.95975312 -1.19583102  1.60340316 -1.0875926   0.27397572  0.54094115
  0.48313426  1.45702602 -1.79363653  2.07193367 -0.61750378  0.72598132
  0.95663619  0.3348168   2.30012317 -1.01561997  0.5359788   1.84457367
 -0.93649683  0.3167739   0.32292453  0.50956534 -0.32491634  2.21739447
 -0.15166692 -1.27153118 -0.06849677  0.60967917  0.58075743 -0.49825428
 -0.55663318  0.57404039  0.65238915 -1.24549013 -0.69888371  1.45618212
  0.49961602  0.55687085  0.16640652  0.51765335 -0.75716456 -0.07143695

In [25]:
# TODO:
# Add b to each row of A
C = A + b
print(C)
# HINT:
# - No reshape required


[[ 2.40881865 -1.42503158  2.17076306 ...  1.46912889 -0.0958292
   1.18301371]
 [ 4.86002184 -1.98497448  1.92736762 ...  0.74928984  0.71882909
  -0.79289775]
 [ 2.26188836 -1.40578026  1.31452659 ... -0.80170806 -0.28832699
   1.6648582 ]
 ...
 [ 2.20554036 -2.58253593  1.40891951 ...  0.81377219 -0.15543649
  -0.2103927 ]
 [ 0.02560375 -0.915549    0.28002833 ...  0.03184084 -1.23147212
   1.90416643]
 [ 2.64355374  0.31869155  3.95040353 ...  0.48900038  0.51760237
   1.57688704]]


In [26]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind

row_sums = A.sum(axis=1, keepdims=True)
A_normalized = A / row_sums

print(A_normalized)

[[ 0.37562424 -0.19171653  0.47457246 ...  1.72846034 -0.19411209
   0.85890964]
 [-0.57772331  0.1571946  -0.06453258 ... -0.26823127 -0.11605063
   0.18905131]
 [ 0.03350371 -0.02328122 -0.03203346 ... -0.02266937 -0.04707962
   0.16729791]
 ...
 [-0.20375223  1.14954793  0.16122267 ... -1.16972839  0.24178951
   0.30387392]
 [ 0.38574064 -0.05589856  0.26392969 ... -0.12546918  0.27277125
  -0.34861453]
 [ 0.05237608  0.11600567  0.17976976 ...  0.08320396  0.02921102
   0.10882045]]


Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [27]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it

A = np.random.randn(1000, 50)
b_bad = np.random.randn(1000)

# Fix: Reshape b_bad to (1000, 1) to enable broadcasting across the 50 columns of A
# C=A + b_bad # This line causes the error
C = A + b_bad[:, np.newaxis]

print(C)

ValueError: operands could not be broadcast together with shapes (1000,50) (1000,) 

What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [28]:
# TODO:
# Create large array X of size 1,000,000

X = np.random.randn(1_000_000)


In [29]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it
import time

X_loop = X.copy()

start = time.time()

total = 0
for x in X_loop:
    total += x

for i in range(len(X_loop)):
    X_loop[i] = X_loop[i] / total

end = time.time()

print("Loop time:", end - start)




Loop time: 0.5924317836761475


In [30]:
# TODO:
# Normalize using vectorization

X_vec = X.copy()

start = time.time()

X_vec = X_vec / X_vec.sum()

end = time.time()

print("Vectorized time:", end - start)


Vectorized time: 0.00829625129699707


Why is vectorization faster?


Task 4.2: Pairwise Distance (FAANG Classic)

In [3]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key
import numpy as np
def pairwise_distance(X):
    X = np.asarray(X, dtype=float)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    sq = np.sum(X * X, axis=1)
    dist2 = sq[:, None] + sq[None, :] - 2 * (X @ X.T)
    dist2 = np.maximum(dist2, 0.0)
    return np.sqrt(dist2)

X = np.random.randn(5, 3)

print(pairwise_distance(X))

print(pairwise_distance(X))


[[0.00000000e+00 1.00897407e+00 2.45005816e+00 2.49931196e+00
  1.53756375e+00]
 [1.00897407e+00 0.00000000e+00 2.43096808e+00 1.86421354e+00
  1.25858662e+00]
 [2.45005816e+00 2.43096808e+00 0.00000000e+00 1.52507258e+00
  1.22508053e+00]
 [2.49931196e+00 1.86421354e+00 1.52507258e+00 2.10734243e-08
  1.12336381e+00]
 [1.53756375e+00 1.25858662e+00 1.22508053e+00 1.12336381e+00
  0.00000000e+00]]
[[0.00000000e+00 1.00897407e+00 2.45005816e+00 2.49931196e+00
  1.53756375e+00]
 [1.00897407e+00 0.00000000e+00 2.43096808e+00 1.86421354e+00
  1.25858662e+00]
 [2.45005816e+00 2.43096808e+00 0.00000000e+00 1.52507258e+00
  1.22508053e+00]
 [2.49931196e+00 1.86421354e+00 1.52507258e+00 2.10734243e-08
  1.12336381e+00]
 [1.53756375e+00 1.25858662e+00 1.22508053e+00 1.12336381e+00
  0.00000000e+00]]


Section 5 — Numerical Stability

Task 5.1: Softmax

In [3]:
# TODO:
# Implement naive softmax
def softmax_naive(X):
    ex = np.exp(X)
    return ex / ex.sum(axis=1, keepdims=True)

def softmax_stable(X):
    Z = X - X.max(axis=1, keepdims=True)
    ex = np.exp(Z)
    return ex / ex.sum(axis=1, keepdims=True)

Xbig = np.array([[1000.0, 1001.0, 1002.0]])
try:
    print('naive:', softmax_naive(Xbig))
except FloatingPointError as e:
    print('overflow:', e)

print('stable:', softmax_stable(Xbig))
print('rowsum:', softmax_stable(Xbig).sum(axis=1))


naive: [[nan nan nan]]
stable: [[0.09003057 0.24472847 0.66524096]]
rowsum: [1.]


/tmp/ipython-input-3995204913.py:4: RuntimeWarning: overflow encountered in exp
  ex = np.exp(X)
/tmp/ipython-input-3995204913.py:5: RuntimeWarning: invalid value encountered in divide
  return ex / ex.sum(axis=1, keepdims=True)


In [ ]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    ...


Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [5]:
# TODO:
# Try valid and invalid matrix multiplications
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

C = np.array([[1, 2, 3]])
D = np.array([[4, 5]])

print(C @ D)


[[19 22]
 [43 50]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [6]:
A = np.random.default_rng(4).standard_normal((3, 4))
B = np.random.default_rng(5).standard_normal((4, 2))
C = A @ B
print('C shape:', C.shape)

C shape: (3, 2)


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [7]:
# TODO:
# Compare in-place vs out-of-place operations
import numpy as np
import time

def compare_inplace_vs_outofplace(n=2_000_000):
    rng = np.random.default_rng(7)
    X = rng.standard_normal(n)
    Y = X.copy()

    start = time.perf_counter()
    Z = X + 1.0
    out_time = time.perf_counter() - start

    start = time.perf_counter()
    Y += 1.0
    in_time = time.perf_counter() - start

    print(f"Out-of-place time: {out_time:.6f} seconds")
    print(f"In-place time    : {in_time:.6f} seconds")

    return out_time, in_time

compare_inplace_vs_outofplace()




Out-of-place time: 0.006384 seconds
In-place time    : 0.001747 seconds


(0.006384377000358654, 0.001747172999785107)

Task 7.2: Strides

In [8]:
# TODO:
# Inspect array strides and explain
import numpy as np

def inspect_strides():
    A = np.arange(24).reshape(6, 4)
    print("A:")
    print("  shape   :", A.shape)
    print("  strides :", A.strides)
    print("  contiguous:", A.flags['C_CONTIGUOUS'])
    print()

    B = A[:, ::2]
    print("B = A[:, ::2]  (every 2nd column)")
    print("  shape   :", B.shape)
    print("  strides :", B.strides)
    print("  contiguous:", B.flags['C_CONTIGUOUS'])
    print()

inspect_strides()



A:
  shape   : (6, 4)
  strides : (32, 8)
  contiguous: True

B = A[:, ::2]  (every 2nd column)
  shape   : (6, 2)
  strides : (32, 16)
  contiguous: False



Section 8 — Mini Case Study

In [9]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

import numpy as np

def pca_project(X, k=5, ddof=1, eps=1e-12):
    X = np.asarray(X, dtype=float)
    n = X.shape[0]

    mu = X.mean(axis=0, keepdims=True)
    sigma = X.std(axis=0, ddof=0, keepdims=True)
    sigma = np.maximum(sigma, eps)
    Xn = (X - mu) / sigma

    C = (Xn.T @ Xn) / (n - ddof)

    eigvals, eigvecs = np.linalg.eigh(C)
    idx = np.argsort(eigvals)[-k:][::-1]

    W = eigvecs[:, idx]
    Z = Xn @ W

    return Z, W, eigvals[idx], mu, sigma, C

rng = np.random.default_rng(8)
X = rng.standard_normal((10_000, 100))

Z, W, top_eigvals, mu, sigma, C = pca_project(X, k=5)

print("C shape:", C.shape)
print("W shape:", W.shape)
print("Z shape:", Z.shape)
print("top eigvals:", top_eigvals)


C shape: (100, 100)
W shape: (100, 5)
Z shape: (10000, 5)
top eigvals: [1.19809266 1.19079564 1.18107089 1.17133948 1.16626579]


Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
